package kyber;

import org.apache.commons.lang3.RandomStringUtils;
import org.bouncycastle.jcajce.SecretKeyWithEncapsulation;
import org.bouncycastle.jcajce.spec.KEMExtractSpec;
import org.bouncycastle.jcajce.spec.KEMGenerateSpec;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider;
import org.bouncycastle.pqc.jcajce.spec.KyberParameterSpec;
import org.bouncycastle.util.encoders.Hex;

import java.nio.charset.Charset;
import java.security.InvalidAlgorithmParameterException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Security;
import java.security.spec.AlgorithmParameterSpec;
import java.util.Base64;
import java.util.Random;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;

public class Main {

    private static final String KEM_ALGORITHM = "Kyber";
    // private static final AlgorithmParameterSpec KEM_PARAMETER_SPEC = KyberParameterSpec.kyber512;
    private static final String PROVIDER = "BCPQC";
    private static final String ENCRYPTION_ALGORITHM = "AES";
    private static final String MODE_PADDING = "AES/ECB/PKCS5Padding"; // ECB mode with PKCS5 padding

    public static String encrypt(String plainText, byte[] key) throws Exception {
        SecretKeySpec secretKey = new SecretKeySpec(key, ENCRYPTION_ALGORITHM);
        Cipher cipher = Cipher.getInstance(MODE_PADDING);
        cipher.init(Cipher.ENCRYPT_MODE, secretKey);
        byte[] encryptedBytes = cipher.doFinal(plainText.getBytes());
        return Base64.getEncoder().encodeToString(encryptedBytes);
    }

    public static String decrypt(String encryptedText, byte[] key) throws Exception {
        SecretKeySpec secretKey = new SecretKeySpec(key, ENCRYPTION_ALGORITHM);
        Cipher cipher = Cipher.getInstance(MODE_PADDING);
        cipher.init(Cipher.DECRYPT_MODE, secretKey);
        byte[] decodedBytes = Base64.getDecoder().decode(encryptedText);
        byte[] decryptedBytes = cipher.doFinal(decodedBytes);
        return new String(decryptedBytes);
    }

    private static KeyPair generateKeyPair(AlgorithmParameterSpec parameterSpec)
            throws NoSuchAlgorithmException, NoSuchProviderException, InvalidAlgorithmParameterException {
        //generate key pair
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance(KEM_ALGORITHM, PROVIDER);
        keyPairGenerator.initialize(parameterSpec, new SecureRandom());
        return keyPairGenerator.generateKeyPair();
    }

    private static SecretKeyWithEncapsulation generateSecretKeySender(PublicKey publicKey)
            throws NoSuchAlgorithmException, NoSuchProviderException, InvalidAlgorithmParameterException {

        // You will request a key generator
        KeyGenerator keyGenerator = KeyGenerator.getInstance(KEM_ALGORITHM, PROVIDER);
        // You will set up a KEM Generate Spec with the public key
        KEMGenerateSpec kemGenerateSpec = new KEMGenerateSpec(publicKey, "Secret");
        // KEMGenerateSpec kemGenerateSpec = new KEMGenerateSpec(publicKey, "AES");
        // Now you can initialize the key generator with the kem generate spec and generate out share secret
        keyGenerator.init(kemGenerateSpec, new SecureRandom());
        return  (SecretKeyWithEncapsulation)keyGenerator.generateKey();
    }

    private static SecretKeyWithEncapsulation generateSecretKeyReciever(PrivateKey privateKey, byte[] encapsulation)
            throws NoSuchAlgorithmException, NoSuchProviderException, InvalidAlgorithmParameterException {

        // You will set up a KEM Extract Spec with the receiver private key - in this case you need the encapsulation
        // generated by the receiver as well.
        KEMExtractSpec kemExtractSpec = new KEMExtractSpec(privateKey, encapsulation, "Secret");

        // You will request a key generator
        KeyGenerator keyGenerator = KeyGenerator.getInstance(KEM_ALGORITHM, PROVIDER);
        // Now you can initialize the key generator with the kem extract spec and retrieve the KEM secret.
        keyGenerator.init(kemExtractSpec);

        return (SecretKeyWithEncapsulation)keyGenerator.generateKey();
    }

    public static void main(String[] args) throws Exception {

        // Let's add the required providers for this exercise
        // the regular Bouncy Castle provider for ECDHC
        Security.addProvider(new BouncyCastleProvider());
        // the Bouncy Castle post quantum provider for the PQC KEM.
        Security.addProvider(new BouncyCastlePQCProvider());
        KyberParameterSpec[] kyberParameterSpecs = {
                KyberParameterSpec.kyber512,
                KyberParameterSpec.kyber768,
                KyberParameterSpec.kyber1024
        };
        
        // String originalText = "This is a secret message.";
        for (int i = 3; i < 26; i++) {
        	String originalText = RandomStringUtils.randomAscii(2 << i);
        	// System.out.println("-Original Text length: " + originalText.length());
        	String str = String.valueOf(i);
	        for (KyberParameterSpec kyberX : kyberParameterSpecs) {
	            // generation of the Crystal Kyber key pair for receiver
	        	long startKeyPair = System.nanoTime();
		        KeyPair keyPair = generateKeyPair(kyberX);
		
		        // System.out.println("---KEM Algorithm: " + keyPair.getPublic().getAlgorithm());
		        // System.out.println("Public Key length: " + keyPair.getPublic().getEncoded().length);
		        // System.out.println("Private Key length: " + keyPair.getPrivate().getEncoded().length);
		
		        SecretKeyWithEncapsulation initKeyWithEnc = generateSecretKeySender(keyPair.getPublic());
		        byte[] encapsulation = initKeyWithEnc.getEncapsulation();
		
		        // System.out.println("Secret created by Sender: " + Hex.toHexString(initKeyWithEnc.getEncoded()));
		        /* byte[] secr = initKeyWithEnc.getEncoded();
		        System.out.println("Length of Secret key: " + secr.length);*/
		        // System.out.println("Length of encapsulated shared secret: " + encapsulation.length);
		        SecretKeyWithEncapsulation recKeyWithEnc = generateSecretKeyReciever(keyPair.getPrivate(), encapsulation);
		        // System.out.println("Secret decapsulated by Receiver: " + Hex.toHexString(recKeyWithEnc.getEncoded()));
		        long totalKeyPair = System.nanoTime() - startKeyPair;
		        //System.out.println("Time Gen Key Pair: " + String.format("%.4f", totalKeyPair / 1000000.0) + " ms");
		        str += " " + String.format("%.1f", totalKeyPair / 1000.0);
		        
		        long startEncrypt = System.nanoTime();
		        String encryptedText = encrypt(originalText, initKeyWithEnc.getEncoded());
		        // System.out.println("Encrypted Text: " + encryptedText.length());
		        // encryptedText = (u, v)
		
		        long totalEncrypt = System.nanoTime() - startEncrypt;
		        str += " " + String.format("%.1f", totalEncrypt / 1000.0);
		        // System.out.println("Time Encrypted: " + String.format("%.4f", totalEncrypt / 1000000.0) + " ms");
		        
		        // SecretKeyWithEncapsulation recKeyWithEnc = generateSecretKeyReciever(keyPair.getPrivate(), encapsulation);
		        // System.out.println("Secret decapsulated by Receiver: " + Hex.toHexString(recKeyWithEnc.getEncoded()));
		        long startDecrypt = System.nanoTime();
		        String decryptedText = decrypt(encryptedText, recKeyWithEnc.getEncoded());
		        // System.out.println("Decrypted Text: (" + decryptedText.equals(originalText) + ") " + decryptedText + "\n");
		        long totalDecrypt = System.nanoTime() - startDecrypt;
		        str += " " + String.format("%.1f", totalDecrypt / 1000.0);
		        // System.out.println("Time Decrypted: " + String.format("%.4f", totalDecrypt / 1000000.0) + " ms");
	        }
	        System.out.println(str);
        }
    }
}